default_stages: [commit]

repos:
- hooks:
  - id: black
  - id: black-jupyter
    language_version: python3.11
  repo: https://github.com/psf/black-pre-commit-mirror
  rev: 24.8.0
- hooks:
  - id: commitizen
  repo: https://github.com/commitizen-tools/commitizen
  rev: v3.29.0
